// Manual project configuration for subfolders and featured repos
export const manualProjects = [
  {
    id: 1,
    name: 'CalmBridge',
    description: 'A calming bridge application',
    technologies: ['JavaScript', 'React'],
    githubUrl: 'https://github.com/PurpleTrex/CalmBridge',
    liveUrl: 'https://purple-apps.vercel.app/',
    imageUrl: '/purpleAppsimg.png',
    stars: 0,
    forks: 0,
    language: 'JavaScript',
    topics: [],
    featured: true,
  },
  {
    id: 2,
    name: 'Risk Portfolio',
    description: 'Risk assessment and portfolio management tool',
    technologies: ['C'],
    githubUrl: 'https://github.com/PurpleTrex/Apps/tree/main/C/Risk%20Portfolio',
    liveUrl: 'https://riskport.vercel.app/',
    imageUrl: '/riskPortImg.png',
    stars: 0,
    forks: 0,
    language: 'C',
    topics: ['portfolio', 'risk-management'],
    featured: true,
  },
  {
    id: 3,
    name: 'Apps Repository',
    description: 'Collection of applications built with various technologies including C, Java, and Python',
    technologies: ['C', 'Java', 'Python', 'Multi-Language'],
    githubUrl: 'https://github.com/PurpleTrex/Apps',
    liveUrl: undefined,
    stars: 0,
    forks: 0,
    language: null,
    topics: ['portfolio', 'multi-language', 'projects'],
    featured: true,
  },
  {
    id: 4,
    name: 'Windows Vault',
    description: 'Secure credential storage for Windows',
    technologies: ['C'],
    githubUrl: 'https://github.com/PurpleTrex/Apps/tree/main/C/Windows%20Vault',
    liveUrl: undefined,
    stars: 0,
    forks: 0,
    language: 'C',
    topics: ['security', 'windows'],
    featured: true,
  },
  {
    id: 5,
    name: 'NotePad',
    description: 'A custom notepad application built with Java',
    technologies: ['Java'],
    githubUrl: 'https://github.com/PurpleTrex/Apps/tree/main/Java/NotePad',
    liveUrl: undefined,
    stars: 0,
    forks: 0,
    language: 'Java',
    topics: ['editor', 'notepad'],
    featured: true,
  },
  {
    id: 6,
    name: 'Snippy',
    description: 'Code snippet manager',
    technologies: ['Python'],
    githubUrl: 'https://github.com/PurpleTrex/Apps/tree/main/py/Snippy',
    liveUrl: undefined,
    stars: 0,
    forks: 0,
    language: 'Python',
    topics: ['snippets', 'productivity'],
    featured: true,
  },
  {
    id: 7,
    name: 'Image Resizer',
    description: 'Batch image resizing utility',
    technologies: ['Python'],
    githubUrl: 'https://github.com/PurpleTrex/Apps/tree/main/py/image%20resizer',
    liveUrl: undefined,
    stars: 0,
    forks: 0,
    language: 'Python',
    topics: ['image-processing', 'utility'],
    featured: true,
  },
];
